USE [M_VPSA_V3]
GO

/****** Object:  StoredProcedure [dbo].[BORRADO_BOLETAS]    Script Date: 08/09/2021 12:05:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- PROCESO DE GENERACION DE INTERESES
CREATE PROCEDURE [dbo].[BORRADO_BOLETAS]
AS
-- DECLARACIÓN DE VARIABLES DE TRABAJO
DECLARE @IdBoleta INT, @FechaVencimiento DATE, @FechaHoy DATE
declare @contador int=0		
set @FechaHoy=GetDate()
		
-- DECLARACIÓN DEL CURSOR
DECLARE MI_CURSOR CURSOR FOR
SELECT B.IdBoleta as IdBoleta, B.FechaVencimiento AS FechaVencimiento
from BOLETA B
where B.FechaVencimiento < @FechaHoy

-- APERTURA DEL CURSOR
OPEN MI_CURSOR
-- LECTURA DEL PRIMER REGISTRO
FETCH NEXT FROM MI_CURSOR INTO @IdBoleta, @FechaVencimiento;
-- RECORRER EL CURSOS MIENTRAS HAYAN REGISTROS
WHILE @@FETCH_STATUS=0 BEGIN
	UPDATE BOLETA SET BHabilitado=0 where IdBoleta = @IdBoleta
-- DECLARACIÓN DEL CURSOR DE LOS DETALLES
	DECLARE @IdDetalleBoleta INT = 0
	DECLARE MI_CURSOR_DETALLES CURSOR FOR
	SELECT D.IdDetalleBoleta as IdDetalleBoleta
	from DETALLEBOLETA D
	where D.IdBoleta = @IdBoleta
	OPEN MI_CURSOR_DETALLES
	FETCH NEXT FROM MI_CURSOR_DETALLES INTO @IdDetalleBoleta;
	WHILE @@FETCH_STATUS=0 BEGIN
		UPDATE DETALLEBOLETA SET BHabilitado=0 where IdDetalleBoleta = @IdDetalleBoleta
		FETCH NEXT FROM MI_CURSOR_DETALLES INTO @IdDetalleBoleta;
	END
	CLOSE MI_CURSOR_DETALLES
-- LIBERAR EL RECURSO
	DEALLOCATE MI_CURSOR_DETALLES;
-- FIN CURSOR DE DETALLES
	set @contador=+1		
FETCH NEXT FROM MI_CURSOR INTO @IdBoleta, @FechaVencimiento;
END 
if(@contador>0)
	INSERT INTO CONTROL_PROCESOS(IdProceso) VALUES (3); 
CLOSE MI_CURSOR
-- LIBERAR EL RECURSO
DEALLOCATE MI_CURSOR;

GO

